### ISSUE TITLE
大兄弟，抄袭我seckil的源码和readme.md，有点意思哦

### ISSUE THREAD

**Issue by codingXiaxw** [justinbaby/spring-mybatis#2]
大兄弟，抄袭我seckil的源码和readme.md，还不标明原作信息，有点意思

**Comment by b1ar7e** [comment]
？？？说的我一脸懵逼。首先我不知道发生了什么。但我先说声抱歉。我确实在慕课网上看到很多评论有源码，我就点进去想看下。我怎么成抄袭了啊……我只是想看看你们写的源码啊？github是我最近刚知道的网站，之前没用过。里面有些单词我不认识，我就想收藏一下以便以后查看。是这里出了问题吗？我真的不懂。我只是个想学知识的大学学生，我没必要去抄袭。你告诉我该怎么做，我马上去弄。如果需要赔偿损失，我也愿意。跟你带来的麻烦真的抱歉，我真的不懂。


发自网易邮箱大师
在2017年02月16日 15:42，夏循武 写道：

大兄弟，知道我写秒杀商品seckill完成README.md花了多长时间吗？然后被你完全抄袭我的代码和README.md，你有提供原作者信息吗？有问过我的意见吗？你知道啥叫开源精神吗？看你README.md后面还附加了License的信息，我倒要问你你懂这个词的含义吗？

孩子，人在抄袭天在看，我的粉丝今天告诉我github上有个完全抄袭了我项目经历的家伙，然后打算过来喷你，我制止了，因为我知道你这种人还是有点自知之明的是吗？

**Comment by codingXiaxw** [comment]
看看你这个秒杀项目的readme.md，再看看我这个项目的readme.md，难道你不觉得完全是抄袭吗？或许是转载？


赔偿我倒不需要，毕竟你还是个什么都不懂的大学生，我只是希望，以后你在转载他人的劳动成果时，不妨写明原内容的来源以及该作者的信息？？？你知不知道自己的劳动成果被别人拿去抄袭然后当做自己的劳动成果，原作会有多气愤？










发自网易邮箱大师
在2017年02月16日 15:58，b1ar7e 写道：
？？？说的我一脸懵逼。首先我不知道发生了什么。但我先说声抱歉。我确实在慕课网上看到很多评论有源码，我就点进去想看下。我怎么成抄袭了啊……我只是想看看你们写的源码啊？github是我最近刚知道的网站，之前没用过。里面有些单词我不认识，我就想收藏一下以便以后查看。是这里出了问题吗？我真的不懂。我只是个想学知识的大学学生，我没必要去抄袭。你告诉我该怎么做，我马上去弄。如果需要赔偿损失，我也愿意。跟你带来的麻烦真的抱歉，我真的不懂。


发自网易邮箱大师
在2017年02月16日 15:42，夏循武 写道：

大兄弟，知道我写秒杀商品seckill完成README.md花了多长时间吗？然后被你完全抄袭我的代码和README.md，你有提供原作者信息吗？有问过我的意见吗？你知道啥叫开源精神吗？看你README.md后面还附加了License的信息，我倒要问你你懂这个词的含义吗？

孩子，人在抄袭天在看，我的粉丝今天告诉我github上有个完全抄袭了我项目经历的家伙，然后打算过来喷你，我制止了，因为我知道你这种人还是有点自知之明的是吗？

**Comment by codingXiaxw** [comment]
b1ar7e 我没说你， 我说的是这个抄袭别人劳动成果的justinbaby

**Comment by codingXiaxw** [comment]
@b1ar7e  我没说你，我说的是这个抄袭别人劳动成果的 @justinbaby

**Comment by b1ar7e** [comment]
关键是我没有想发表的意思…………我只是想收藏以后自己看啊。。应该是我没有弄对。对不起。我到宿舍就会删除。真的对不起。


发自网易邮箱大师
在2017年02月16日 16:04，夏循武 写道：
看看你这个秒杀项目的readme.md，再看看我这个项目的readme.md，难道你不觉得完全是抄袭吗？或许是转载？


赔偿我倒不需要，毕竟你还是个什么都不懂的大学生，我只是希望，以后你在转载他人的劳动成果时，不妨写明原内容的来源以及该作者的信息？？？你知不知道自己的劳动成果被别人拿去抄袭然后当做自己的劳动成果，原作会有多气愤？










发自网易邮箱大师
在2017年02月16日 15:58，b1ar7e 写道：
？？？说的我一脸懵逼。首先我不知道发生了什么。但我先说声抱歉。我确实在慕课网上看到很多评论有源码，我就点进去想看下。我怎么成抄袭了啊……我只是想看看你们写的源码啊？github是我最近刚知道的网站，之前没用过。里面有些单词我不认识，我就想收藏一下以便以后查看。是这里出了问题吗？我真的不懂。我只是个想学知识的大学学生，我没必要去抄袭。你告诉我该怎么做，我马上去弄。如果需要赔偿损失，我也愿意。跟你带来的麻烦真的抱歉，我真的不懂。


发自网易邮箱大师
在2017年02月16日 15:42，夏循武 写道：

大兄弟，知道我写秒杀商品seckill完成README.md花了多长时间吗？然后被你完全抄袭我的代码和README.md，你有提供原作者信息吗？有问过我的意见吗？你知道啥叫开源精神吗？看你README.md后面还附加了License的信息，我倒要问你你懂这个词的含义吗？

孩子，人在抄袭天在看，我的粉丝今天告诉我github上有个完全抄袭了我项目经历的家伙，然后打算过来喷你，我制止了，因为我知道你这种人还是有点自知之明的是吗？
