### ISSUE TITLE
我是查关键字秒杀系统进来的，然后有个星星最多的就点进来的

### ISSUE THREAD

**Issue by Se7enGo** [justinbaby/spring-mybatis#4]
然后看了 README.md 说的codingXiaxw的开发文档，但是没有连接，所以就想在问题区补上一个，然后就看见原作者已经发现了这个问题了。不过为了避免戳进来学习的兄弟懵逼，这里还是贴上原作者的博客，另外还有他的开发文档地址：
博客：http://codingxiaxw.cn/  
秒杀系统开发文档：
Java高并发秒杀系统API(一)之DAO层开发 http://codingxiaxw.cn/2016/11/27/53-maven-ssm-seckill-dao/ 
Java高并发秒杀系统API(二)之Service层开发  http://codingxiaxw.cn/2016/11/28/54-seckill-service/
Java高并发秒杀系统API(三)之Web层开发  http://codingxiaxw.cn/2016/11/28/55-seckill-web/ 

最后向开源精神致敬，另：以上内容如有问题的话请联系我处理。

**Comment by justinbaby** [comment]
加上了：)
